import {Nunito} from 'next/font/google';
import React, {ReactNode} from 'react';

import {Navigation} from '@components/organism';
import '@styles/global.css';
import {RootStyleRegistry, ThemeProvider} from '@lib/styled-components';
import theme, {ColorScheme} from '@styles/theme';

const font = Nunito({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({children}: {children: ReactNode}) => (
  <html lang="ko">
    <body className={font.className}>
      <RootStyleRegistry>
        <ThemeProvider theme={theme[ColorScheme.LIGHT]}>
          <Navigation />
          <div className="content">{children}</div>
        </ThemeProvider>
      </RootStyleRegistry>
    </body>
  </html>
);

export default RootLayout;
